# Generated by Django 4.2.1 on 2023-06-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_tweet', '0004_rename_meeps_meep'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
