# Generated by Django 4.2.1 on 2023-06-12 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_tweet', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='likes',
            field=models.ManyToManyField(related_name='meep_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
